config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
end

app/models/user.rb
class User
  include ActiveAttr::Model

  attribute :first_name
  attribute :last_name
  attribute :ip_address
  attribute :phone_distance_from_ip
  attribute :stated_distance_from_ip
  attribute :stated_distance_from_phone

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
require 'net/http'
require 'timeout'

class UsersController < ApplicationController

  def create
    @user = User.new
    @user.first_name = params["first_name"]
    @user.last_name = params["last_name"]
    @user.ip_address = params["ip_address"]

    begin
      status = Timeout::timeout(5) do

        @user = CalculateDistance.new(@user)

        render json: @user
      end
    rescue Timeout::Error
      render json: "Your Request timeout out, please try again later"
    end
  end

  def new

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/check_locations_helper.rb
module CheckLocationsHelper
end

app/views/check_locations/new.html.erb
<h2>Location Verification Form</h2>

<form action="<%= users_url %>" method="post">
    <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

    <label>First Name</label>
    <input type="text" name="first_name" value="">
    <br>

    <label>Last Name</label>
    <input type="text" name="last_name" value="">
    <br>

    <label>IP Address</label>
    <input type="text" name="ip_address" value="">
    <br>

    <input type="submit" value="Check Identity">
  </form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IdentityVerificationApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h2>Location Verification Form</h2>

<form action="<%= check_locations_url %>" method="post">
    <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

    <label>First Name</label>
    <input type="text" name="first_name" value="">
    <br>

    <label>Last Name</label>
    <input type="text" name="last_name" value="">
    <br>

    <label>IP Address</label>
    <input type="text" name="ip_address" value="">
    <br>

    <input type="submit" value="Check Identity">
  </form>